const purchasesData = [
    {
        id: "1",
        product: "Dolor Adipisicing",
        store: "Netplax",
        price: "$1,786.06",
        purchaseData: "2018-03-16",
        address: "411 Lorraine Street, Motley, Colorado, 3419",
    },
    {
        id: "2",
        product: "Pruident Dolore Consectetur",
        store: "Enquility",
        price: "$2,922.38",
        purchaseData: "201=7-09-11",
        address: "277 Haring Street, Soudan, Utah, 3276",
    },
    {
        id: "3",
        product: "Magna Aliqua Id",
        store: "Xoggle",
        price: "$1,237.49",
        purchaseData: "2017-04-24",
        address: "177 Clinton Avenue, Sterling, New Mexico, 305",
    },
    {
        id: "4",
        product: "Fugliat Ullamco Do",
        store: "Ecraze",
        price: "$3,225.90",
        purchaseData: "2018-11-30",
        address: "546 Indiana Place, Bynum, Hawaii, 1679",
    },
    {
        id: "5",
        product: "Proident Laborum",
        store: "Chillium",
        price: "$1,304.96",
        purchaseData: "2018-1-28",
        address: "296 Benson Avenue, Coventry, Arizona, 1652",
    },
    {
        id: "6",
        product: "Do Tempor",
        store: "Honotron",
        price: "$3,154.18",
        purchaseData: "2019-04-24",
        address: "230 Perry Terrace, Wolcott, Nevada, 3533",
    },
    {
        id: "7",
        product: "Nostrud Ad",
        store: "Pawnagra",
        price: "$1,813.40",
        purchaseData: "2014-10-18",
        address: "107 Poly Place, Southmont, Virginia, 2477",
    },
    {
        id: "8",
        product: "Proident Eiusmod Commodo Consectetur",
        store: "Ersum",
        price: "$3,012.73",
        purchaseData: "2020-07-12",
        address: "841 Portland Avenue, Sanborn, Iowa, 3273",
    },
    {
        id: "9",
        product: "Occaecat Nulla",
        store: "Squish",
        price: "$2,311.89",
        purchaseData: "2020-03-21",
        address: "545 Kingsway Place, Como, Louisiana, 545",
    },
    {
        id: "10",
        product: "Quis Consequat Pariatur",
        store: "Lotron",
        price: "$3,921.57",
        purchaseData: "2019-08-06",
        address: "895 Falmouth Street, Herbster, Michigan, 5023",
    },
];

export default purchasesData;